# Generated by Django 6.1 on 2026-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(choices=[('UP_TO_DATE', 'Up to date'), ('PARTIALLY_VACCINATED', 'Partially vaccinated'), ('NOT_VACCINATED', 'Not vaccinated')], max_length=20),
        ),
    ]
