# Generated by Django 6.1 on 2026-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_vaccination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='microchip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
