# Generated by Django 6.1 on 2026-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_microchip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
