# Generated by Django 6.1 on 2026-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_age_alter_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(choices=[('VACCINATED', 'Vaccinated'), ('PARTIALLY_VACCINATED', 'Partially vaccinated'), ('NOT_VACCINATED', 'Not vaccinated')], max_length=20),
        ),
    ]
