# Generated by Django 6.1 on 2026-09-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_bio_doctorprofile_clinic_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_address',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_mode',
        ),
    ]
